yarnPath: .yarn/releases/yarn-3.3.1.cjs
packageExtensions:
  # https://github.com/firebase/firebase-js-sdk/issues/3707
  "@firebase/database@*":
    peerDependencies:
      "@firebase/auth": "*"
      "@firebase/app": "*"
